services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: wordpress
      MYSQL_USER: usr-wordpress
      MYSQL_PASSWORD: pwd-wordpress
    networks:
      - wordpress-net
    volumes:
      - ./mysql_data:/var/lib/mysql 

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql-db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-net
    depends_on:
      - mysql-db

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql-db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-net
    depends_on:
      - mysql-db

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql-db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-net
    depends_on:
      - mysql-db

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    networks:
      - wordpress-net
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3

networks:
  wordpress-net:
    driver: bridge